### ISSUE TITLE
More instructions needed

### ISSUE THREAD

**Issue by TakingItCasual** [TkTech/PyNBT#12]
I'm pulling my hair out here guessing how to properly navigate through the NBT structure. 

In my case, I need to iterate through a TAG_LIST, taking a TAG_STRING with a known key from each TAG_COMPOUND and comparing against it. If a match is found I want to modify another TAG_STRING with a known key within the same TAG_COMPOUND, and if a match isn't found I want to create a new TAG_COMPOUND and fill it. Finally, I want to write the changes to the file I read from.

I'm essentially trying to modify an IP for a specific name within MC's servers.dat file.

**Comment by TkTech** [comment]
In PyNBT a `TAG_List` is just a `list`, and a `TAG_Compound` is just a `dict`. You can treat them exactly the same way you would the native python types.

**Comment by TakingItCasual** [comment]
So I've gotten navigation working:

    with open('servers.dat', 'rb') as io:
        nbt_file = NBTFile(io)

        for serverIndex in nbt_file[u'servers']:
            if serverIndex['name'].value == server_title:
                serverIndex['ip'].value = new_server_ip

But how do I save nbt_file to an nbt formatted file?

**Comment by TakingItCasual** [comment]
So I've gotten navigation working:

    with open('servers.dat', 'rb') as io:
        nbt_file = NBTFile(io)

        for serverIndex in nbt_file[u'servers']:
            if serverIndex[u'name'].value == server_title:
                serverIndex[u'ip'].value = new_server_ip

But how do I save nbt_file to a file? (servers2.dat) comes out blank when I try the following:

    with open('servers2.nbt', 'wb') as io2:
        nbt_file.save(io2)
