### ISSUE TITLE
Use bytearray for TAG_Byte_Array

### ISSUE THREAD

**Issue by alexiscoutinho** [TkTech/PyNBT#18]
In `map_<#>.dat` files, of the `data` folder, pixel color IDs are not read like unsigned bytes as expected. By the way, shouldn't this TAG be stored with the native `bytearray` class to save memory?

**Comment by TkTech** [comment]
It will stay as a bytearray. If you need it as a signed array, just `array.array('b', tag.value)` is enough to get you what you want.
